{"name": "Ошибка авторизации курьера с несуществующим логином", "status": "passed", "start": 1743008866199, "stop": 1743008866366, "uuid": "4af6185f-8bdf-477d-a631-15a1d169e121", "historyId": "11ad4d04f52427c01fdabebe0ec8c13d", "testCaseId": "11ad4d04f52427c01fdabebe0ec8c13d", "fullName": "tests.test_login_courier.TestLoginCourier#test_not_existed_login_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Natalia_Ivanova"}, {"name": "thread", "value": "48168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}