{"name": "Ошибка при создании курьера с существующим логином", "status": "passed", "start": 1743008726044, "stop": 1743008726370, "uuid": "718f2e94-11ef-4127-8fc7-bab3498a77a9", "historyId": "89579da75853808ed683d1fda86505ab", "testCaseId": "89579da75853808ed683d1fda86505ab", "fullName": "tests.test_create_courier.TestCreateCourier#test_same_login_two_couriers_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Natalia_Ivanova"}, {"name": "thread", "value": "50768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}