{"name": "Ошибка авторизации курьера с несуществующим логином", "status": "passed", "start": 1743008790569, "stop": 1743008790768, "uuid": "9cd88fda-d5b6-4696-8a04-27974311b36a", "historyId": "11ad4d04f52427c01fdabebe0ec8c13d", "testCaseId": "11ad4d04f52427c01fdabebe0ec8c13d", "fullName": "tests.test_login_courier.TestLoginCourier#test_not_existed_login_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Natalia_Ivanova"}, {"name": "thread", "value": "50768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}